****Домашнее задание к занятию «Python для анализа данных: numpy и scipy»****
    
***Задание 1***
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [102]:
import numpy as np

n = 10
np.arange(n-1, 0-1, -1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [103]:
np.linspace(n-1, 0, n)

array([9., 8., 7., 6., 5., 4., 3., 2., 1., 0.])

***Задание 2***

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [108]:
import numpy as np

n = 10
total = 0
x = np.diag(np.arange(n-1, 0-1, -1), k=0)
print(x)

for i in range(0, n):
    total += x[i][i]
    
print(total)

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
45


***Задание 3***

Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [91]:
import pandas as pd
movies = pd.read_csv("ml-latest-small/movies.csv")
ratings = pd.read_csv("ml-latest-small/ratings.csv")
ratings.head()

#было непросто найти метод index.tolist(), чтобы получить значения id фильма, 
#так как .values в данном случае возвращает число упоминаний, а первый столбец отбрасывает
data = ratings[ ratings.rating == 5.0 ]['movieId'].value_counts().head(1)
movie_count = data.values[0]
movie_id = data.index.tolist()[0] 

print(movies[ movies.movieId == movie_id].values[0][1], ":" , movie_count)

Shawshank Redemption, The (1994) : 153


In [92]:
#попробовала собрать в 1 запрос, но такое нагромождения скорее всего сложно понять
print(movies[ movies.movieId == ratings[ ratings.rating == 5.0 ]['movieId'].value_counts().head(1).index.tolist()].values[0][1])

Shawshank Redemption, The (1994)


***Задание 4***

По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [127]:
import pandas as pd
power = pd.read_csv("power.csv")

data = power[ ((power['country'] == 'Latvia') | (power['country'] == 'Lithuania') | (power['country'] == 'Estonia')) & 
      ((power['category'] == 4) | (power['category'] == 12) | (power['category'] == 21)) & 
      ( power['year'] >= 2005) & ( power['year'] <= 2010) & 
      ( power['quantity'] >= 0) ].groupby('country').sum().filter(items = ['country', 'quantity'])
print(data)

print("\nОбщее потребление стран Латвия, Литва, Эстония = " ,
      data.sum().filter(items = ['quantity']).values[0])


           quantity
country            
Estonia     63440.0
Latvia      54844.0
Lithuania  122296.0

Общее потребление стран Латвия, Литва, Эстония =  240580.0


***Задание 5***

Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [138]:
import numpy as np

a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])                           # коэффициенты при переменных в левой части уравнения
b = np.array([4, 12, -3])                                                 # значения в правой части уравнения
c = linalg.solve(a, b)                                                    # решение
print("x = {} \ny = {} \nz = {}\n".format(c[0], c[1], c[2]))

x = 0.4666666666666668 
y = 3.844444444444444 
z = -5.555555555555555

