****Лабораторная работа по модулю “Python для анализа данных”****

Списки и строки – одни из важных начальных понятий для любого дата сайентиста, поскольку на знании принципов работы с ними строится работа с препроцессингом и обработкой данных в python в целом и работы с модулем pandas в частности:

1.1 Дан произвольный список, содержащий только числа. Выведите результат сложения всех чисел больше 10.


In [1]:
array = [1, 5, 5.1, 7, 10, 11.8, 5, 7, 101, 1111111]
sum = 0
for x in array:
    if x > 10:
        sum += x
print(sum)

1111223.8


1.2 Пусть задан список, содержащий строки. Выведите все строки, заканчивающиеся буквой r.

In [3]:
array = ['flat', 'dog', 'error', 'moor', 'hi', 'peer']
for x in array:
    if x[-1] == 'r':
        print(x)

error
moor
peer


1.3 Сгенерируйте и выведите cлучайную строку размером 6 символов, содержащую только цифры. Строка должна содержать хотя
бы одну цифру 3.

In [3]:
import random
while True:
    x = []
    for i in range(6):
        x.append(random.randint(0, 9))
    if 3 in x:
        str_ = ''.join(str(e) for e in x)
        print(str_)
        break

352522


In [1]:
s = "-"
seq = ("a", "b", "c") # Это последовательность строк.
print (s.join( seq ))

a-b-c


1.4 Пусть дана строка произвольной длины. Выведите информацию о том, сколько в ней символов и сколько слов.

In [8]:
str = 'kl ah sdlhkied bhkeckehbc kel/eqdcke; /dkedjnewkjeb dkwbdkb felf;elfkq'
print(len(str), 'symbols')
print(len(str.split(' ')), 'words')

70 symbols
8 words


-----------------------------------------------------------------------------------
Матрицы-следующее за списками и строками важное понятие. Широко используется в линейной алгебре. Находит свое
применение в современных рекомендательных системах и архитектуре нейронных сетей:

2.1 Пусть дана матрица чисел размером NхN. Представьте данную матрицу в виде списка. Выведите результат сложения всех элементов матрицы.

In [27]:
import numpy as np

n = 6
x = np.arange( 0, n*n )
x = x.reshape(n, n)                  #получили матрицу

x = x.reshape(1, n*n)[0]          #получили список из матрицы
print(x)
print(sum(x))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
630


2.2 Дана матрица размером NxM. Напишите алгоритм вычисления максимума из сумм элементов каждого столбца.

In [43]:
import numpy as np

n = 10
m = 5
x = np.arange( 0, n*m )
x = x.reshape(n, m)                     #получили матрицу
print(x)

sums = x[0]
for i in range(1, n):
    for j in range(0, m):
        sums[j] += x[i][j]
        
print("\n",max(sums))    
    



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]

 265


Работа с динамичными структурами важная часть в имплементации вашего кода в продакшн систему:

3.1 Пусть список студентов представлен в виде структуры [[No, ФИО, Возраст,Группа],[No, ФИО, Возраст, Группа],[No, ФИО, Возраст, Группа]].

Преобразуйте список в словарь вида: {No: [ФИО, Возраст, Группа], No:[....], No: [....]}

In [1]:
students = [[0, "Иванов Петр Карлович", 19, "121"],
            [1, "Иванов Игнат Петрович", 28, "121-1"],
            [3, "Шульгина Алия Львовна", 17, "121-1"]]
studens_dict = dict()

for student in students:
    studens_dict[student[0]] = student[1:]
    
print(studens_dict)

{0: ['Иванов Петр Карлович', 19, '121'], 1: ['Иванов Игнат Петрович', 28, '121-1'], 3: ['Шульгина Алия Львовна', 17, '121-1']}


3.2 Напишите алгоритм, позволяющий найти запись в словаре из задачи 3.1 (без преобразования словаря обратно в список) по фамилии и изменить в ней номер группы. Фамилию и новый номер группы необходимо ввести с клавиатуры.

In [2]:
#поскольку уточнений нет - будем менять группу всем с такой фамилией
name = input()
group = input()

for value in studens_dict.values():
    if name in value[0]:
        value[2] = str(group)

print(studens_dict)

Иванов
145
{0: ['Иванов Петр Карлович', 19, '145'], 1: ['Иванов Игнат Петрович', 28, '145'], 3: ['Шульгина Алия Львовна', 17, '121-1']}


3.3 Напишите алгоритм, позволяющий аналогично задаче 3.2 изменить возраст студента

In [3]:
#здесь будем менять возраст только первому с такой фамилией
name = input()
age = input()

for value in studens_dict.values():
    if name in value[0]:
        value[1] = age
        break

studens_dict

Иванов
23


{0: ['Иванов Петр Карлович', '23', '145'],
 1: ['Иванов Игнат Петрович', 28, '145'],
 3: ['Шульгина Алия Львовна', 17, '121-1']}