****Домашнее задание к занятию «Python для анализа данных: numpy и scipy»****
    
***Задание 1***
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [102]:
import numpy as np

n = 10
np.arange(n-1, 0-1, -1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [103]:
np.linspace(n-1, 0, n)

array([9., 8., 7., 6., 5., 4., 3., 2., 1., 0.])

***Задание 2***

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [108]:
import numpy as np

n = 10
total = 0
x = np.diag(np.arange(n-1, 0-1, -1), k=0)
print(x)

for i in range(0, n):
    total += x[i][i]
    
print(total)

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
45


***Задание 3***

Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

***Задание 4***

По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

***Задание 5***

Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3